version: "3.4"
name: dotnet-app

services:
  backend:
    build:
      context: ./src/Dotnet.Telemetry.Jaeger.Api
      dockerfile: Dockerfile
    container_name: test_application
    ports:
      - "5000:80"
    environment:
      Otlp__Endpoint: http://otel-collector:4317
      Jaeger__Url: jaeger
      Jaeger__Port: 6831
    depends_on:
      - otel-collector
    networks:
      - app_network

  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger
    volumes:
      - "./jaeger-config/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - LOG_LEVEL=debug
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
      - PROMETHEUS_QUERY_NAMESPACE=span_metrics
      - PROMETHEUS_QUERY_DURATION_UNIT=s
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.29.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - app_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.61.0
    container_name: otel-collector
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133"
      - "4317:4317" # OTLP gRPC receiver
    networks:
      - app_network

  grafana:
    image: grafana/grafana:9.4.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - app_network
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards

  seq:
    container_name: seq
    image: datalust/seq:preview
    ports:
      - "5341:80"
      - "5342:5342"
      - "45341:45341"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - app_network

networks:
  app_network:
